"""
TrustShield AI — Prometheus Metrics & Observability Instrumentation.

Tracks:
- HTTP request counters & latency histograms
- Model inference & Trust Engine evaluation latency
- Redis & Neo4j operation latency
- Operational decision distribution (ALLOW, REVIEW, HOLD, BLOCK)
- SSE active connections & events emitted
- Infrastructure fallback counters (Redis offline, Neo4j fallback)
- Forensic dossier generation metrics
"""

from __future__ import annotations

import logging
from typing import Optional

from prometheus_client import (
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
    CONTENT_TYPE_LATEST,
)

logger = logging.getLogger(__name__)

# Standard latency buckets (1ms to 5s)
LATENCY_BUCKETS = (
    0.001, 0.002, 0.005, 0.010, 0.025, 0.050, 0.100, 0.250, 0.500, 1.0, 2.5, 5.0
)

# Shared collector registry
REGISTRY = CollectorRegistry(auto_describe=True)

# -----------------------------------------------------------------------------
# 1. HTTP Layer Metrics
# -----------------------------------------------------------------------------
REQUESTS_TOTAL = Counter(
    "trustshield_requests_total",
    "Total HTTP requests handled by endpoint, method, and HTTP status code.",
    ["endpoint", "method", "status_code"],
    registry=REGISTRY,
)

REQUEST_DURATION_SECONDS = Histogram(
    "trustshield_request_duration_seconds",
    "HTTP request end-to-end latency in seconds.",
    ["endpoint"],
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)

# -----------------------------------------------------------------------------
# 2. Model & Scoring Intelligence Metrics
# -----------------------------------------------------------------------------
DECISIONS_TOTAL = Counter(
    "trustshield_decisions_total",
    "Distribution of operational decisions routed by the Unified Trust Engine.",
    ["decision", "risk_level", "model_version"],
    registry=REGISTRY,
)

MODEL_INFERENCE_SECONDS = Histogram(
    "trustshield_model_inference_seconds",
    "Raw ML classifier predict_proba latency in seconds.",
    ["model_version"],
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)

TRUST_ENGINE_SECONDS = Histogram(
    "trustshield_trust_engine_latency_seconds",
    "Composite Canonical Trust Engine evaluation latency in seconds.",
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)

# -----------------------------------------------------------------------------
# 3. Infrastructure & Fallback Metrics
# -----------------------------------------------------------------------------
REDIS_LATENCY_SECONDS = Histogram(
    "trustshield_redis_latency_seconds",
    "Redis feature store / embedding cache round-trip latency in seconds.",
    ["operation"],
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)

NEO4J_LATENCY_SECONDS = Histogram(
    "trustshield_neo4j_latency_seconds",
    "Neo4j Cypher graph query execution latency in seconds.",
    ["query_name"],
    buckets=LATENCY_BUCKETS,
    registry=REGISTRY,
)

FALLBACK_TOTAL = Counter(
    "trustshield_fallback_total",
    "Count of observable fallbacks triggered due to infrastructure unavailability.",
    ["subsystem", "reason"],
    registry=REGISTRY,
)

# -----------------------------------------------------------------------------
# 4. Investigation & Forensic Dossier Metrics
# -----------------------------------------------------------------------------
DOSSIER_GENERATION_TOTAL = Counter(
    "trustshield_dossier_generation_total",
    "Total forensic dossiers generated by entity type and outcome status.",
    ["entity_type", "status"],
    registry=REGISTRY,
)

DOSSIER_DURATION_SECONDS = Histogram(
    "trustshield_dossier_duration_seconds",
    "Forensic dossier generation pipeline latency in seconds.",
    buckets=(0.010, 0.050, 0.100, 0.250, 0.500, 1.0, 2.0, 5.0, 10.0),
    registry=REGISTRY,
)

# -----------------------------------------------------------------------------
# 5. Real-Time Streaming (SSE) Metrics
# -----------------------------------------------------------------------------
SSE_ACTIVE_CLIENTS = Gauge(
    "trustshield_sse_active_clients",
    "Number of active Server-Sent Events (SSE) streaming connections.",
    registry=REGISTRY,
)

SSE_EVENTS_TOTAL = Counter(
    "trustshield_sse_events_total",
    "Total transaction events emitted over the SSE real-time stream.",
    registry=REGISTRY,
)


class MetricsService:
    """Wrapper exposing metrics recording and Prometheus format serialization."""

    def __init__(self):
        self.requests_total = REQUESTS_TOTAL
        self.request_duration = REQUEST_DURATION_SECONDS
        self.decisions_total = DECISIONS_TOTAL
        self.model_inference_seconds = MODEL_INFERENCE_SECONDS
        self.trust_engine_seconds = TRUST_ENGINE_SECONDS
        self.redis_latency_seconds = REDIS_LATENCY_SECONDS
        self.neo4j_latency_seconds = NEO4J_LATENCY_SECONDS
        self.fallback_counter = FALLBACK_TOTAL
        self.dossier_total = DOSSIER_GENERATION_TOTAL
        self.dossier_duration = DOSSIER_DURATION_SECONDS
        self.sse_clients_gauge = SSE_ACTIVE_CLIENTS
        self.sse_events_counter = SSE_EVENTS_TOTAL

    def record_decision(self, decision: str, risk_level: str, model_version: str) -> None:
        self.decisions_total.labels(
            decision=decision,
            risk_level=risk_level,
            model_version=model_version,
        ).inc()

    def record_fallback(self, subsystem: str, reason: str) -> None:
        self.fallback_counter.labels(subsystem=subsystem, reason=reason).inc()

    def export_metrics(self) -> bytes:
        """Serialize registered metrics to Prometheus exposition format."""
        return generate_latest(REGISTRY)


metrics_service = MetricsService()
